### ISSUE TITLE
Error while building MAUI project when using .NET 9.0 : System.UnauthorizedAccessException 

### ISSUE THREAD

**Issue by rahulshreebastav** [dotnet/android#9564] opened 2024-11-28 06:48 UTC
### Android framework version

net9.0-android

### Affected platform version

VS 2022 Version 17.12.2, .Net 9.0

### Description

Errors :
  System.UnauthorizedAccessException: Access to the path 'projetcpath\obj\Debug\net9.0-android\android\assets\x86_64\project.dll' is denied.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.File.InternalDelete(String path, Boolean checkHost)
     at Microsoft.Android.Build.Tasks.Files.CopyIfChangedOnce(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 197
     at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 176
     at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 394
     at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 161
     at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 76
     at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

I frequently encounter errors when building the Android project. Restarting Visual Studio or deleting the obj folder temporarily resolves the issue, allowing the build to succeed. However, the problem reappears whenever I make changes and attempt to rebuild. This issue was not present in .NET 8.0, but after upgrading to .NET 9.0, the errors occur consistently. I need a permanent solution to resolve this problem

### Steps to Reproduce

1. First Build -> Build Success without any errors.
2. Changes in files/project -> Try to rebuild again then get an issues.

The first build completes successfully without any issues.
After making changes to the project and trying to rebuild, errors occur during the build process.

### Did you find any workaround?

Yes, but I am not getting any  permanent solutions .

### Relevant log output

```shell

```

**Comment by dellis1972** [comment] 2024-11-28 08:51
This is a duplicate of https://github.com/dotnet/android/issues/9133

**Closed by dellis1972** 2024-11-28 08:51 UTC
Labels: Area: App+Library Build, needs-triage
