### ISSUE TITLE
Xamarin Android release 9.4.0.51 does not work with Microsoft InTune for Android release 3.0.4821.1

### ISSUE THREAD

**Issue by ghost** [dotnet/android#3429] opened 2019-08-01 20:21 UTC
### Steps to Reproduce

When using Visual Studio for Mac 8.2.1 that uses Xamarin Android release 9.4.0.51 the Microsoft InTune SDK for Android nuget package version 3.0.4821.1 with remapper package version 0.1.4428.1 no longer function properly.  Xamarin Android applications built with this release of tools will build and run, but will not make it past the Application class required by the InTune SDK.  Any attempt to put break points in the MainActivity class will not be hit and the application doesn't make past this when looking at logcat.  

Any project that uses the latest nuget package for InTune will not work.  We have validated ALL projects including a new app from scratch suffers from this issue.  A copy of our Mobile Reference App can be found here:
https://github.com/biozal/Xamarin-Forms-Reference-App

### Expected Behavior
Application launches and functions properly.

### Actual Behavior
Applications freezes on the Application class and never hits the MainActivity class.

### Version Information
=== Visual Studio Community 2019 for Mac ===
Version 8.2.1 (build 19)
Installation UUID: a9e154d1-445b-4050-96eb-81e67f29a730
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)
   Package version: 600000311
 === Mono Framework MDK ===
Runtime:
    Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
    Package version: 600000311
=== NuGet ===
Version: 5.1.0.6013
=== .NET Core ===
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    2.1.12
    2.1.11
    2.1.9
    2.1.8
    2.1.7
    2.1.2
    2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
    2.1.701
    2.1.700
    2.1.505
    2.1.504
    2.1.503
    2.1.302
    2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks
=== Xamarin.Profiler ===
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
=== Updater ===
Version: 11
=== Apple Developer Tools ===
Xcode 10.2.1 (14490.122)
Build 10E1001
=== Xamarin.Mac ===
Version: 5.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400
=== Xamarin.iOS ===
Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400
=== Xamarin Designer ===
Version: 16.2.0.375
Hash: 357d38ef4
Branch: remotes/origin/d16-2
Build date: 2019-07-26 14:44:54 UTC
=== Xamarin.Android ===
Version: 9.4.0.51 (Visual Studio Community)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/pl945qz/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        5.0 (API level 21)
        5.1 (API level 22)
        6.0 (API level 23)
        7.0 (API level 24)
        7.1 (API level 25)
        8.0 (API level 26)
        8.1 (API level 27)
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 27.0.3
Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
 == Microsoft Mobile OpenJDK ===
Java SDK: /Users/pl945qz/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
=== Android Device Manager ===
Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC
=== Xamarin Inspector ===
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1
=== Build Information ===
Release ID: 802010019
Git revision: c7aee29ba7d2a827dbfe4901e4ad7249ce7e5bc7
Build date: 2019-07-29 20:22:23+00
Build branch: release-8.2
Xamarin extensions: c990de17e8456ead7fce80aff9dab01df769b2fd
=== Operating System ===
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

InTune Android for Xamarin Nuget Packages:
https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.Android/
https://www.nuget.org/packages/Microsoft.Intune.MAM.Remapper.Tasks/

### Log File
[com.eygsl.atf.pulse.log.zip](https://github.com/xamarin/xamarin-android/files/3458511/com.eygsl.atf.pulse.log.zip)
[com.eygsl.ctmob.speedup.log.zip](https://github.com/xamarin/xamarin-android/files/3458512/com.eygsl.ctmob.speedup.log.zip)
[pulse-08012019-1220pm.log](https://github.com/xamarin/xamarin-android/files/3458514/pulse-08012019-1220pm.log)
[speedapp-08012019-1215pm.log](https://github.com/xamarin/xamarin-android/files/3458515/speedapp-08012019-1215pm.log)

**Comment by biozal** [comment] 2019-08-01 20:51
@JonDouglas - Meghan.Daly@microsoft.com from the InTune Android team has the Company Portal logs.  I'm not sure how much those will help.  The Incident ID over there is:  YKP22DQE.

**Comment by jonathanpeppers** [comment] 2019-08-01 20:57
The linked sample doesn't build for me:
```
Intune\Enrollment\EnrollmentService.cs(21,9): error CS0535: 'EnrollmentService' does not implement interface member 'IEnrollmentService.RegisterAndEnrollAccountAsync(Endpoint)'
Intune\Enrollment\EnrollmentService.cs(21,9): error CS0535: 'EnrollmentService' does not implement interface member 'IEnrollmentService.LoginAndEnrollAccountAsync(Endpoint, string)'
Intune\Enrollment\EnrollmentService.cs(21,9): error CS0535: 'EnrollmentService' does not implement interface member 'IEnrollmentService.DeRegisterAndUnenrollAccountAsync(bool)'
```
It looks like the `IEnrollmentService` interface changed:
```csharp
Task RegisterAndEnrollAccountAsync(Endpoint endPoint);
Task LoginAndEnrollAccountAsync(Endpoint endpoint, string identity = null);
Task DeRegisterAndUnenrollAccountAsync(bool withWipe = false);
```
The app has:
```csharp
void RegisterAndEnrollAccount(Endpoint endPoint)
void LoginAndEnrollAccount(Endpoint endPoint, string identity = null)
void DeRegisterAndUnenrollAccount(bool withWipe = false)
```

Does this sample need to be updated for this new interface? https://github.com/biozal/Xamarin-Forms-Reference-App

I remember looking at another InTune sample, I'll see if I can find it in the meantime.

**Comment by biozal** [comment] 2019-08-01 20:58
let me double check - this should have built I merged out our corporate changes, I might have missed something.

**Comment by biozal** [comment] 2019-08-01 21:07
@jonathanpeppers  - merged fixes, compiles now.  I can also provide real apps source code or apk if helps, just can't post here.

**Comment by jonathanpeppers** [comment] 2019-08-01 22:20
The symptom I'm seeing here is a white app -- as if you made an `Activity` with a blank or missing `OnCreate`. There is also a warning that would indicate that breakpoints may not work:

    Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly

If I view `obj\Debug\90\android\assets\Mobile.RefApp.CoreUI.Android.dll` in ILSpy, it is indeed missing `OnCreate`, and the base class is the regular `FormsAppCompatActivity`:

![image](https://user-images.githubusercontent.com/840039/62330794-53209000-b47f-11e9-9eea-e19dec2e13e5.png)

And `FormsAppCompatActivity` looks like:

![image](https://user-images.githubusercontent.com/840039/62331011-1d2fdb80-b480-11e9-9eea-4eb6b75c8a27.png)

So I have another sample I used when looking at InTune's SDKs that still seems to be working, probably because it does not use Xamarin.Forms: https://github.com/jonathanpeppers/IntuneRepro/tree/workaround

But it looks like this:

![image](https://user-images.githubusercontent.com/840039/62330751-3be1a280-b47f-11e9-8596-23f22a75bb56.png)

So my guess, is this NuGet package: https://www.nuget.org/packages/Microsoft.Intune.MAM.Remapper.Tasks/

It is probably meant to change the base type of `FormsAppCompatActivity` to `MAMAppCompatActivity`. But we will need to ask the owner's of the InTune NuGet packages to know what it is supposed to be doing here. I can help them figure out what changed. 

@meghandaly are you the right person to ask about this?

**Comment by biozal** [comment] 2019-08-02 01:39
@jonathanpeppers We used the sample from @meghandaly here: 
https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps

In that example it shows not to change the MainActivity.cs:

https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/blob/master/TaskrForms/TaskrForms.Android/MainActivity.cs

This matches the SDK documentation:
https://docs.microsoft.com/en-us/intune/app-sdk-xamarin#xamarinforms-integration

There is a nuget package that handles the remapping of classes:
https://www.nuget.org/packages/Microsoft.Intune.MAM.Remapper.Tasks/

It's supposed to make an MSBuild step.  So if I look at the nuget package contents I can find the remapping-config.json file that does the remapping.  In that file I see under ClassRewrites:

      "Class": {
        "From": "android.app.Activity",
        "To": "com.microsoft.intune.mam.client.app.MAMActivity"
      }

      "Class": {
        "From": "android.support.v7.app.AppCompatActivity",
        "To": "com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivity"
      },

Based on this it's mapping  FormsAppCompatActivity based on it inheriting from android.support.v7.app.AppCompatActivity.

**Comment by biozal** [comment] 2019-08-02 01:54
@jonathanpeppers looking into this further I think it's because of the msbuild target file:
Microsoft.Intune.MAM.Remapper.Tasks.targets

So I took the remapping-config.json file and put it into my Android UI project and changed the Build action to RemappingConfigFile and compiled and ran my application and now it works.  

So I believe the error is in the msbuild target file of the remapper nuget package and that this defect should be with the InTune team to resolve.  

For now the work around for us is to check in the remapping-config.json file into our source if we want to use the new version of VS for Mac.  I'll validate this with a few other of our apps quickly to make sure the fix works with all our apps, but based on your analysis and mine, I don't believe the target config file is telling remapper to run properly.


![Screen Shot 2019-08-01 at 9 51 29 PM](https://user-images.githubusercontent.com/176927/62338460-a22deb80-b4a6-11e9-8cc3-8286e1883a0c.png)

**Comment by jonathanpeppers** [comment] 2019-08-02 14:03
From the build log:

![image](https://user-images.githubusercontent.com/840039/62375277-8a388500-b503-11e9-9e3d-98533183479f.png)

That file exists, but I wonder if there is a mistake in the `json` or something. I see a similar mapping, but I guess it is not working:

```json
      "Class": {
        "From": "android.support.v7.app.AppCompatActivity",
        "To": "com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivity"
      },
```

I'm not sure I see how updating to XA 9.4 could have caused this, could updating the NuGet package have been the cause?

**Comment by biozal** [comment] 2019-08-02 14:54
@jonathanpeppers we have had the same nuget package for weeks before the XA 9.4.  All I can tell you is if I use the remapping-config.json file and set the built type like I described above our apps are working.  I've tested four of them now and they all work with XA 9.4.  My educated guess is that it's a combination of MS Build updates in VS for Mac 8.2 and it detecting things that might have changed in XA 9.4 that is causing the issue.

**Comment by meghandaly** [comment] 2019-08-02 15:27
We are aware of the issue and will be working with the Xamarin team to look into it further. I don't have anything more to add to the investigation at this time, unfortunately.

**Comment by saikiran-adimulam-by** [comment] 2020-06-13 14:49
@biozal Can you please share the remapping-config.json file

**Comment by saikiran-adimulam-by** [comment] 2020-06-23 10:35
@biozal Can you please share the config file

**Comment by saikiran-adimulam-by** [comment] 2020-06-24 10:51
My Android MainActivity is inherited from Xamarin.Forms.Platform.Android.FormsAppCompatActivity and I have added the remapping-config file and changed the build action accordingly. 
Remapping config file has below code for Activity but still my app is not working
"Class": {
        "From": "android.support.v7.app.AppCompatActivity",
        "To": "com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivity"
      },

@biozal Could you please help me in resolving the issue

**Comment by Aniiia** [comment] 2022-03-06 15:08
Hi,

any new things on that?

Greetings,
Anja

**Comment by jpobst** [comment] 2024-06-18 13:59
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.

**Closed by jpobst** 2024-06-18 13:59 UTC
Labels: regression
