### ISSUE TITLE
`aapt2` fails for file paths containing umlauts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/android#9472] opened 2024-10-30 20:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net9-blazor-maui-hybrid-app---Android-A/10778853)._

---
[severity:I'm unable to use this version]
create a new .net9 blazor maui hybrid app
use following project and solution name: ABÖ

Error Message:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	APT2000
c# kann folgende datei nicht finden Das System kann die angegebene Datei nicht finden. (2): C:\Users\reinh\source\repos\ABÖ\ABÖ\ABÖ\obj\Debug\net9.0-android\assets.

C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.2.152\tools\Xamarin.Android.Aapt2.targets

Reason:
If there is a umlaut in the name, Android cannot be compiled

ABÖ -> notworking
ABO -> working

---
#### Feedback Bot on 10/29/2024, 06:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by dellis1972** [comment] 2024-10-31 08:44
This is down to https://issuetracker.google.com/issues/188679588

So this is a duplicate of https://github.com/dotnet/android/issues/6925

**Closed by dellis1972** 2024-10-31 08:44 UTC
Labels: Area: App+Library Build
