### ISSUE TITLE
"Cannot access a disposed object" when reading large JSON from Web

### ISSUE THREAD

**Issue by DelphinRP** [dotnet/android#9262] opened 2024-08-27 09:51 UTC
### Description

Hello everyone,

we are deserializing a large JSON reply from our web server. The source code has been generated with `NSwag.CodeGeneration.CSharp` and used to work fine with WPF, .NET MAUI iOS and .NET MAUI Android. Since a few weeks ago, the functionality has stopped working with .NET MAUI Android and sporadically throws `ObjectDisposedException` exceptions. Both WPF and iOS work fine.

We have not found out why and how this occurs. The only big change we had in the last few weeks was updating Visual Studio and .NET MAUI workloads.

**EDIT:** The error does not occur in .NET MAUI 8.0.61

### Steps to Reproduce

```csharp
    try
    {
        using (var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
        using (var streamReader = new System.IO.StreamReader(responseStream))
        using (var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader))
        {
            var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
            var typedBody = serializer.Deserialize<T>(jsonTextReader);
            return new ObjectResponseResult<T>(typedBody, string.Empty);
        }
    }
    catch (Newtonsoft.Json.JsonException exception)
    {
        var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
        throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
    }
```

The exception occurs on `return new ObjectResponseResult<T>(typedBody, string.Empty);`.

### Version with bug

8.0.72

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Unfortunately, we could not find any workaround.

### Relevant log output

```bash
 dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------------------
android                    34.0.113/8.0.100       SDK 8.0.400, VS 17.11.35219.272
aspire                     8.1.0/8.0.100          SDK 8.0.400, VS 17.11.35219.272
ios                        17.5.8020/8.0.100      SDK 8.0.400, VS 17.11.35219.272
maccatalyst                17.5.8020/8.0.100      SDK 8.0.400, VS 17.11.35219.272
maui-windows               8.0.72/8.0.100         SDK 8.0.400, VS 17.11.35219.272
```

```shell
System.ObjectDisposedException: Cannot access a disposed object.

 Object name: 'Java.IO.InputStreamInvoker'.
    at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 57
    at Java.IO.InputStream.Close() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.IO.InputStream.cs:line 116
    at Android.Runtime.InputStreamInvoker.Close() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/InputStreamInvoker.cs:line 62
    at System.IO.Stream.Dispose()
    at System.IO.BufferedStream.Dispose(Boolean disposing)
    at System.IO.Stream.Close()
    at System.IO.Stream.Dispose()
    at System.IO.DelegatingStream.Dispose(Boolean disposing)
    at System.IO.Stream.Close()
    at System.IO.StreamReader.Dispose(Boolean disposing)
    at System.IO.StreamReader.Close()
    at Newtonsoft.Json.JsonTextReader.Close()
    at Newtonsoft.Json.JsonReader.Dispose(Boolean disposing)
    at Newtonsoft.Json.JsonReader.System.IDisposable.Dispose()
    at PSServerClients.Api.V5_0.Client.<ReadObjectResponseAsync>d__87`1[[System.Collections.Generic.List`1[[PSServerClients.Api.V5_0.ShortProject, PSServerClients, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /builds/software/profisignal-20/psserver-clients/PSServerClients/Api/V5_0/Client.cs:line 7102
```

**Comment by jpobst** [comment] 2024-10-30 19:16
Duplicate of https://github.com/dotnet/android/issues/9039.

**Closed by jpobst** 2024-10-30 19:16 UTC
Labels: Area: HTTP
