### ISSUE TITLE
UnauthorizedAccessExceptions are getting raised when building a blank MAUI app when using .NET 9.0

### ISSUE THREAD

**Issue by whodges** [dotnet/android#9133] opened 2024-07-10 18:52 UTC
### Description

I just moved to MAUI 9 this morning (specifically 9.0.0-preview.6.24327.7).  I was using .NET 8.0 prior to this and everything was fine.  I noticed that the first build of solution would work fine, but if I did a rebuild all, the build would fail with an UnauthorizedAccessException.  The only way I can get it to go away is to close and reopen VS (I'm using 17.11.0 Preview 3.0, for the record, running in admin mode on Win 10).  After that, it builds again, but only once before I start getting the UnauthorizedAccessExceptions.

To investigate, I made a blank .NET MAUI 8 app and tried it - everything builds fine.  You can 'Rebuild All' as many times as you want and it'll compete successfully.

Then I made a blank .NET MAUI 9 app and built it - it was fine the first time.  Then I tried 'Rebuild All' and, unfortunately, ran into the same UnauthorizedAccessExceptions during the build:

```
Error (active)	XARDF7019	System.UnauthorizedAccessException: Access to the path 'GoogleGson.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Xamarin.Android.Tasks.RemoveDirFixed.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/RemoveDirFixed.cs:line 54	MauiApp2 (net9.0-android)	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-preview.6.340\tools\Xamarin.Android.Common.targets	2503
```

and

```
Error (active)	XALNS7019	System.UnauthorizedAccessException: Access to the path 'D:\Projects\MauiApp2\obj\Debug\net9.0-android\android\assets\armeabi-v7a\MauiApp2.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 125
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 344
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 161
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 76
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25	MauiApp2 (net9.0-android)	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-preview.6.340\tools\Xamarin.Android.Common.targets	1407
```

These all seem to be Android-releated.  And when I try to deploy the successful build to my Android device, I get this error:

```
Error		XA0127: Error deploying 'files/.__override__/arm64-v8a/ar//Microsoft.Maui.Controls.resources.dll' using 'xamarin.sync: error: could not open 'files/.__override__/arm64-v8a/ar//Microsoft.Maui.Controls.resources.dll'.'.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.
```

I never got this error with .NET 8.0.  Again, this is a fresh MAUI 9.0 app.

### Steps to Reproduce

1. Create a new, default .NET MAUI 9.0 app (use 9.0.0-preview.6.24327.7).
2. Rebuild it.  It should succeed.
3. Rebuild it again.  It should fail with an UnauthorizedAccessException.

### Link to public reproduction project repository

https://github.com/whodges/mauiapp1

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.70

### Affected platforms

Android

### Affected platform versions

Android 31

### Did you find any workaround?

Close and restart Visual Studio (but you'll only get one build out of it).

### Relevant log output

[binlog_success.zip](https://github.com/user-attachments/files/16170070/binlog_success.zip)
[binlog_fail.zip](https://github.com/user-attachments/files/16170069/binlog_fail.zip)
[binlog_deploy_fail.zip](https://github.com/user-attachments/files/16170098/binlog_deploy_fail.zip)

**Comment by jonathanpeppers** [comment] 2024-08-06 18:07
The last error:
```
Error		XA0127: Error deploying 'files/.__override__/arm64-v8a/ar//Microsoft.Maui.Controls.resources.dll' using 'xamarin.sync: error: could not open 'files/.__override__/arm64-v8a/ar//Microsoft.Maui.Controls.resources.dll'.'.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.
```
Should be fixed in:
* https://github.com/xamarin/monodroid/pull/1530
* https://github.com/dotnet/android/pull/9171

Which should hopefully be in .NET 9 Preview 7.

**Comment by jonathanpeppers** [comment] 2024-08-06 21:41
I tried with the .NET 9 Preview 7 build we are working on, I can't seem to reproduce the `UnauthorizedAccessException` even with 4 Rebuilds:

![image](https://github.com/user-attachments/assets/f9abe6f0-6ab4-4e36-94a7-9b4d0896ba64)

If you are having this issue, can you use a tool like [ProcessExplorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to find out what process is locking the file:

```
System.UnauthorizedAccessException: Access to the path 'GoogleGson.dll' is denied.
```

**Comment by whodges** [comment] 2024-08-07 12:31
I tried both procexp and tasklist; unfortunately neither reports that any program currently has the file in use.  I dug in a bit more though and found that every file in `obj\Debug\net9.0-android\android\assets\armeabi-v7a` is locked (that is, if you try and delete it via Explorer, you'll get a "the file is open in another program" error, though any unlocking utility will report the file as being unlocked).  That program is obvious either VS or related to VS, as closing VS unlocks that directory and its files (and a Rebuild will then work - but just once because then `obj\Debug\net9.0-android\android\assets\armeabi-v7a` gets locked again).

**Comment by dellis1972** [comment] 2024-08-07 13:06
@whodges 

Do you have any third party Visual Studio extensions installed (just trying to eliminate causes) for things like code formatting or intellisense. 
What kind of Anti Virus do you have installed?
Do you use hot reload?

Those files are clearly being locked by VS but its odd that it does not show up in the procexp 🤔

**Comment by whodges** [comment] 2024-08-07 13:44
The only non-MS extensions I have are Multiline Search and Replace (Helixsoft) and Xamarin.Android SDK.  AV is just MS Defender.  But on the other Win 10 system I tried this on, there's no AV and no extensions installed.  Yes I have Hot Reload active on both, but just tried disabling it to no avail; the same error occurs.

**Comment by jonathanpeppers** [comment] 2024-08-07 13:52
I tested this on a DevBox/Virtual Machine, and I noticed the project by default is saved on a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/).

Let me just check if anything different happens on a regular drive where Windows Defender will do its standard scanning on file writes.

@whodges does anything different happen if you have a Windows Defender exclusion for the folder where the project is saved?

**Comment by whodges** [comment] 2024-08-07 14:25
Just tried the exclusion; no luck

**Comment by foximoxi** [comment] 2024-09-02 14:46
I've got similar issue.

17.12.0 Preview 1.0/.NET9 Preview 7 -> New MAUI project -> Build:

Output:
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 125
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 344
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 161
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 76
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
   
   It works when I start VS as Administrator.

**Comment by whodges** [comment] 2024-09-02 15:13
Interesting - it happens for me running VS as admin no matter what after the first build.

I also wonder if it could be some regional settings for whatever weird reason?  I’m in Canada.

**Comment by jonathanpeppers** [comment] 2024-09-05 19:59
This will help diagnose these types of issues:
* https://github.com/dotnet/android-tools/pull/242

But it looks like I should add `UnauthorizedAccessException`, which is perhaps thrown by `File.Delete()`?

**Comment by pjeremic** [comment] 2024-09-11 21:19
Hi! 
In my situation, MsBuild.exe holds onto .dll files. If I kill that specific MsBuild instance (identified using Process Explorer), I can build the app again.
Additionally, I’ve noticed that if I wait for a minute or so, the process eventually releases the .dll files, allowing me to build once more.
While there’s no specific reproducible scenario, I’ve observed that certain workflows trigger this issue with locked app .dll files (it's not always the app dll, for example once it was the CommunityToolkit.Mvvm.dll):

Case 1:

1. Build the app.
2. Run it.
3. Close the app in the emulator.
4. Make a small code change to ensure that the app needs recompilation.
5. Attempt to build and deploy.

Case 2:

1. The app is running in the emulator.
2. Make a small code change to ensure that the app needs recompilation.
3. Press hot reload.
4. Stop the app.
5. Attempt to build and deploy.

Case 3:

1. The app is running in the emulator.
2. Press the restart button (Ctrl+Shift+F5).
4. Stop the app.
5. Make a small code change to ensure that the app needs recompilation.
6. Attempt to build and deploy.

Important Note: I’ve tried the mentioned scenarios with a blank/sample app using .NET 8.0 LTS, and it works perfectly. Additionally, deployment to the emulator also seems faster.

TargetFrameworks: net9.0-android;net9.0-ios;net9.0-maccatalyst
VS: 17.12.0 Preview 1.0
Emulator: Pixel 5- API 34 (Android 14.0 - API 34)

**Comment by pjeremic** [comment] 2024-09-13 20:19
@jonathanpeppers 

Sorry for the late reply.
I’ve updated Visual Studio and .NET, but unfortunately, it hasn’t resolved the issue.

[BuildLogs.zip](https://github.com/user-attachments/files/16998921/BuildLogs.zip)

**Comment by jonathanpeppers** [comment] 2024-09-13 21:08
In your case, the file is: `obj\Debug\net9.0-android\android\assets\x86_64\MauiApp2.dll`

Seems like only two tasks would touch it, looking at these logs:
* `<LinkAssembliesNoShrink/>` would do `Files.CopyIfChanged()`
* `<FastDeploy/>` would open the file for reading, and deploy

There are some changes to how the `DirectoryAssemblyResolver` is `Dispose()`d in .NET 9:

https://github.com/dotnet/android/blob/932113927d217d8d9dbc3db029f75ae3426c303e/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs#L90

This is running for a single architecture, `x86_64`, but I don't think I see an issue in here offhand. It looks like it would be `Dispose()`d.

/cc @grendello @dellis1972

**Comment by dellis1972** [comment] 2024-09-13 21:53
My guess is with the IDE closed and building from the command line this is not happening.
There is something in the IDE probably a Design Time build which is locking these files it seems.

**Comment by jonpryor** [comment] 2024-10-01 00:02
The *reporting* for this issue *may* be improved due to dotnet/android-tools@ab2165da.  (Does it work for directories as well as files?)

**Comment by jonathanpeppers** [comment] 2024-10-01 02:20
Maybe this also needs to check `Directory.Exists()`:
* https://github.com/dotnet/android-tools/blob/ab2165daf27d4fcb29e88bc022e0ab0be33aff69/src/Microsoft.Android.Build.BaseTasks/UnhandledExceptionLogger.cs#L97

I would also need to test in what ways that could happen. I don't offhand remember if .NET has an easy API that locks a directory (like `Directory.OpenHandle()`???), but there are definitely Windows p/invoke's that could be used.

**Comment by whodges** [comment] 2024-10-01 16:02
If it helps, here are my latest success (1st rebuild) and failure (2nd rebuild) binlogs using the latest MAUI workload and VS 17.12.0 Preview 2.1.

[success.binlog.zip](https://github.com/user-attachments/files/17212686/success.binlog.zip)
[failure.binlog.zip](https://github.com/user-attachments/files/17212687/failure.binlog.zip)

**Comment by dellis1972** [comment] 2024-10-01 16:14
@whodges can you install [Project System Tools extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022) and capture the design time bin logs as well? 
Also have you tried to reproduce from just the command line (i.e no IDE open).

**Comment by whodges** [comment] 2024-10-01 17:51
The command line (dotnet build --no-incremental) works perfectly fine on its own.  If, however, I have the IDE open, and have used it to build the solution once, both the IDE and the command line will fail with the same `UnauthorizedAccessException`, suggesting that it is indeed the IDE that's locking the Android files.

Design binlogs attached (not sure if I captured them right by I think I did)

[design binlogs.zip](https://github.com/user-attachments/files/17213813/design.binlogs.zip)

**Comment by dellis1972** [comment] 2024-10-11 08:09
@whodges Thanks for the logs. Unfortunately they do not have the error in them?
Both the android based logs have succeeded. If you get a moment try to repo it with the logger on.

**Comment by whodges** [comment] 2024-10-11 13:45
The design time logs or the build logs?  It seems like the design time logs get generated when you open the solution rather than when you build it?

**Comment by dellis1972** [comment] 2024-10-11 13:53
> The design time logs or the build logs? It seems like the design time logs get generated when you open the solution rather than when you build it?

So what we need is all the logs. So open the IDE and kick of the binlogs collection tool. Open your solution and try to repo the issue. Once you get the UnauthorizedAccessException, then stop the logging and send us all the logs. 
We need to get an idea of which design time were running at the time the error occured.

**Comment by berga0d** [comment] 2024-10-13 21:19
Same here, it can't delete the dll

**Comment by maverikou** [comment] 2024-10-15 17:17
Workaround for now is to keep killing the lingering msbuild processes.

**Comment by dellis1972** [comment] 2024-10-15 18:23
I wonder if there is a way to set the start arguments for the msbuild process which is causing the issue?

**Comment by shushu789** [comment] 2024-10-16 02:57
I also encountered almost the same problem, but my current solution is to switch to Windows Machine, stop it and switch back to Android, and it will return to normal. In addition, this problem happens occasionally, even if I don't modify any code. I am currently using Visual Studio 2022 v17.12 preview 2, .net 9 rc2, and the project was created using the "maui-blazor-web" template

**Comment by whodges** [comment] 2024-10-16 04:19
Corrected logs attached - sorry for the wait

[binlogs.zip](https://github.com/user-attachments/files/17389140/binlogs.zip)

**Comment by whodges** [comment] 2024-11-18 20:18
Yeah.  Still happens for me too.  I can't use .NET 9 because of it; stuck on 8.

**Comment by dellis1972** [comment] 2024-11-18 20:57
The issue here is Defender is locking these files. We added some additional handling in .net 9 which should report which program has the file or directory locked.

**Comment by Sascha-L** [comment] 2024-11-19 15:08
So please reopen this issue.  With previous version everything is working fine, after upgrading you have to restart Visual Studio or kill hundreds of msbuild processes EVERYTIME you change your code und build your solution...  so it is impossible to work anymore and this issue happens for everyone, this is a BIG ISSUE which needs an urgent Hot Fix!

**Comment by arahmancsd** [comment] 2024-11-19 15:50
This still happens in the latest VS 17.12 and it is frustrating. Every edit seems to cause the error and you can't run your MAUI project smoothly. It only works once/twice when you close VS.

**Comment by dellis1972** [comment] 2024-11-19 15:53
@Sascha-L @arahmancsd do you have the logs for the errors you are seeing? We need to collect data

**Comment by Sascha-L** [comment] 2024-11-19 15:57
@dellis1972 Create a MAUI project, start debugging with Android Emulator, stop, change code, run again. That's it. It will happen to you too. So no logs are needed, when this issue happens for everyone.

**Comment by dellis1972** [comment] 2024-11-19 16:00
@Sascha-L  I have never been able to repo this on the devbox's I have access to, and it does not happen on macos. 
Also there are various points in the build where this issue might happen unless you are getting the exact `XARDF7019` error?

**Comment by dellis1972** [comment] 2024-11-19 16:15
So you can try to set the following environment variables these control how we try to retry file writes in .net 9 android.

```
DOTNET_ANDROID_FILE_WRITE_RETRY_ATTEMPTS=10
DOTNET_ANDROID_FILE_WRITE_RETRY_DELAY_MS=1000
```

The defaults as as above. You can try to change these to see if they make any difference.

**Comment by whodges** [comment] 2024-11-19 16:49
I've tried to repeat the build process with Windows Defender disabled, and this file locking still occurs, so I don't think it's the culprit.  Nor do I believe the retry attempts/delays will accomplish anything as this isn't a timing issue:  the files are locked and they'll continue to be locked until the IDE is closed and restarted.

I appreciate it's very, very difficult to diagnose/solve a problem when you can't reproduce it.  I've been there many times myself.  I'm happy to help in anyway possible to help solve this, either by following some steps or even granting you remote access to my system for testing.  Like I said before, I'm running Windows 10 on a physical machine (not a VM).

What do we know:  this only happens with .NET 9, and not with 8 and earlier.  It's also tied to Android.  So what's changed in .NET 9 with the Android build process?

I've attached the latest binlog the build failure.

[MauiApp1_Debug_AnyCPU_Build_2024-11-19T11_36_59.0220817-05_00.zip](https://github.com/user-attachments/files/17818578/MauiApp1_Debug_AnyCPU_Build_2024-11-19T11_36_59.0220817-05_00.zip)

**Comment by whodges** [comment] 2024-11-19 16:55
To clarify my previous comment:  if you uncheck 'Enable targeting of the Android platform' in the project properties, these locking errors go away.

**Comment by dellis1972** [comment] 2024-11-19 17:02
Ok, so the initial investigation led us to believe that it was Defender causing this issue and that the retry code we put in place would help. I'm going to re-open this issue since this does not appear to be the case. 

@jonathanpeppers can you remember the url for the instructions to install the System tools which allow users to see which processes have files locked?

**Comment by jonathanpeppers** [comment] 2024-11-19 17:20
I think Sysinternals Process Explorer is the easiest one to use:

* https://learn.microsoft.com/sysinternals/downloads/process-explorer

**Comment by dellis1972** [comment] 2024-11-19 18:20
@whodges (or anyone else) do you have any third party extensions installed in Visual Studio?

**Comment by whodges** [comment] 2024-11-19 18:34
My extensions:

![Image](https://github.com/user-attachments/assets/f8d00769-6b7e-42f6-a689-bbd4ec1c7787)

**Comment by pjeremic** [comment] 2024-11-19 19:31
My extensions:
 

1. Align Assignments 2022
2. Copy As Html 2022
3. Double-Click Maximize 2022
4. Fix Mixed Tabs 2022
5. Match Margin 2022
6. MAUI App Accelerator
7. Middle Click Scroll 2022
8. Peek Help 2022
9. Productivity Power Tools 2022
10. Productivity Power Tools Options Page 2022
11. Shrink Empty Lines 2022
12. Solution Error Visualizer 2022
13. Time Stamp Margin 2022
14. Visual Studio Theme Pack
15. WakaTime
16. WixSharp Project Templates


I don't know where to get a list of installed extensions (without typing all of the names), so I did it like this, in case anyone needs it.

Open PowerShell in this location:

`C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\<VS-VERSION>\Extensions`

Run this command to get the extensions:

`Get-ChildItem extension.vsixmanifest -Recurse | Select-String -Pattern '<DisplayName>(.*?)<\/DisplayName>' | ForEach-Object { $_.Matches[0].Groups[1].Value } | Sort-Object`

@dellis1972

**Comment by dellis1972** [comment] 2024-11-19 23:10
@OvrBtn @whodges @pjeremic  Thanks for the info that is all very useful. 

So its a background build in VS which is causing the lock. 

Next step is to install the "Project System Tools" extension and turn on the "Build Logging" which will log every build VS does. Then repo the issue, and look to see what "builds" were running at the time. 

Just to test, I dusted off my old Surface Pro and installed VS community 2022 with .net 9 to see if I can repo. No luck so far :(

**Comment by dellis1972** [comment] 2024-11-19 23:14
Never mind , we found the issue we think thants @OvrBtn ! 

Next this is to figure out how to fix it

**Comment by Barry-Theunissen** [comment] 2024-11-20 02:33
@OvrBtn devenv or MSBuild.exe is not showing up in the processs explorer like you get...it worked once, but not anymore after a second try to build...why is this?

**Comment by amryakout2024** [comment] 2024-11-28 07:43
i got the same issue with .net9
need to restart and rebuild the project to bypass this error 
then appears again and again

**Comment by Barry-Theunissen** [comment] 2024-11-28 08:11
@amryakout2024 Yes...it is still an issue...but I think it has been fixed...we need to wait for the patch release to .NET 9 I think...not sure when that will be though

**Comment by Michealdgreat** [comment] 2024-11-28 19:46
I am also having the same issue. So annoying that I have to restart VS every time to have a successful build.  Version 17.12.2

**Comment by maverikou** [comment] 2024-11-28 20:09
> I am also having the same issue. So annoying that I have to restart VS every time to have a successful build. Version 17.12.2

You don't.

Run `taskkill /IM "msbuild.exe" /F` instead.

**Comment by Michealdgreat** [comment] 2024-11-28 21:03
> > I am also having the same issue. So annoying that I have to restart VS every time to have a successful build. Version 17.12.2
> 
> You don't.
> 
> Run `taskkill /IM "msbuild.exe" /F` instead.

I have dev-tunneling an Api locally on the same machine, so running this would also kill the msbuild for the api as well. We need an actual fix not a walk around.

**Comment by Michealdgreat** [comment] 2024-11-28 22:28
> > > > I am also having the same issue. So annoying that I have to restart VS every time to have a successful build. Version 17.12.2
> > > 
> > > 
> > > You don't.
> > > Run `taskkill /IM "msbuild.exe" /F` instead.
> > 
> > 
> > I am dev-tunneling an Api locally on the same machine, so running this would also kill the msbuild for the api as well. We need an actual fix not a work around.
> 
> The issue is already fixed and all we are waiting for is the next release.
> 
> As for other workaround did you try just killing the process that is blocking the file instead of killing all `MSBuild.exe` processes? Alternatively can you use .NET 8 for development and .NET 9 just for the release builds?

Good to hear that it's been fixed. 

I tried killing the msbuild for the MAUI, it works sometimes, but most of the times it doesn't work.

I didn't kill all of msbuild as the other one is for the API powering the application.

**Comment by SantosVictorero** [comment] 2024-11-30 20:50
> The issue is already fixed and all we are waiting for is the next release.

Great, glad to hear that! :thumbsup:

**Comment by snydesc** [comment] 2024-12-05 18:00
I just updated to visual studio 17.12.3 which was released today and the problem still happens.

running` taskkill /IM "msbuild.exe" /F` does not solve the problem

**Comment by Barry-Theunissen** [comment] 2024-12-06 02:17
Yes, the problem is still not solved - I am seeing the same thing with 17.12.3

**Comment by dellis1972** [comment] 2024-12-06 09:27
There were a couple of fixes in this area. The commit https://github.com/dotnet/android/commit/be53aed593ffc3863d3df1114d97d2b5e1d6239f might well have been related. And GitHub Auto closed this Issue when that PR was merged. 

That said is it more accurate that PR https://github.com/dotnet/android/pull/9531 fixes this issue. This has been cherry-picked to the .net 9 release branch via https://github.com/dotnet/android/commit/974a5ab29029987898e56f0e455f5cddd16a1f52. I'm not sure when that is being released though. @jonpryor any ideas when that commit will actually make it into a release? 

If anyone is seeing this on the 17.12.3 please get us binlogs of the issue (with the error in it) as it will give us some pointers as to what is going on .

**Comment by dellis1972** [comment] 2024-12-06 10:00
It looks like the "fix" was released in .NET Android SDK 35.0.24. 
You can check to see which version you have in "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows" You should have a 35.0.24 folder if that has been released.

**Comment by dellis1972** [comment] 2024-12-06 10:07
I ran the 17.12.3 update on a VM and I can confirm that the .NET Android 35.0.24 update is not present. I also ran `dotnet workload update` to make sure. Looks like the fix has not yet been released. 
I will leave this issue open until 35.0.24 actually gets released.

**Comment by wjsimon** [comment] 2024-12-06 15:02
> The fix is inserted in the next VS 17.13 Preview, but we will also ship it to NuGet.org.

Are binlogs from the error on 17.12.3 still of interest then? I could provide if yes.

**Comment by jonathanpeppers** [comment] 2024-12-10 18:57
This released today:
* https://github.com/dotnet/android/releases/tag/35.0.24

So, you can install either VS 17.13 Preview 2, or run `dotnet workload update` to get the latest Android workload. Thanks!

**Comment by whodges** [comment] 2024-12-10 19:49
Just tried it and it works for me!  Thanks!

**Closed** 2024-12-10 22:21 UTC
Labels: Area: App+Library Build, regression
