### ISSUE TITLE
.NET Maui - running basic template project has a runtime error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/android#9427] opened 2024-10-18 16:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Maui---running-basic-template-proje/10771485)._

---
After some issues with an attempted Maui upgrade to an existing Xamarin project, in an attempt to understand Maui a little better I decided to just make a brand new Maui project from the basic templates that are found in Visual Studio. I chose the ".NET MAUI Multi-Project App" option, and then when asked what project types to include, chose only iOS and Android.

This template does not build successfully right out of the box, though. I'll describe below the modifications that were made to get past the build stage of this process, in case it is relevant.

Upon creation, it loads in a solution with only one iOS project and one Android project, nothing else. If you try to build this you will get two errors saying it cannot find a dll file somewhere in a /obj folder in the main project, which is created with the template but not included in the solution when you initially start. So I added the project, built THAT, and the errors went away.

After that, I received an error stating (filepath truncated) "Assets file '~\MauiTestApp\MauiTestApp.iOS\obj\project.assets.json' doesn't have a target for 'net8.0-ios/ios-arm64'"

After Googling for a solution to this I found a hint saying to add this to the iOS project's csproj:

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
	<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

After adding this, it did build successfully. However, this is where I cannot progress. When I try to run the Android version in an Android emulator (Pixel 5, Android 13.0 - API 33), at runtime while the app is loading up, this occurs:

![android error.PNG](https://aka.ms/dc/image?name=B48427ced4d9b4405a688b3fec2f71369638647922214498044_android_error.PNG&tid=48427ced4d9b4405a688b3fec2f71369638647922214498044)

Text of the error for searching purposes: Java.Lang.NoClassDefFoundError: 'Failed resolution of: Landroidx/startup/R$string;'

I have googled for similar issues and have not had much luck in finding any clear solutions. As mentioned, the only modifications I have made are what were necessary to get it running. Can anyone give me a hint as to what I might be missing?

PC is running on Windows 10, version 10.0.19045 

Visual studio information (and installed tools as that is included in the 'About' window): 
Microsoft Visual Studio Professional 2022
Version 17.11.5
VisualStudio.17.Release/17.11.5+35327.3
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00483-00100-36538-AA059
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0

ASA Service Provider   1.0

ASP.NET and Web Tools   17.11.231.19466

Azure App Service Tools v3.0.0   17.11.231.19466

Azure Data Lake Tools for Visual Studio   2.6.5000.0

Azure Functions and Web Jobs Tools   17.11.231.19466

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0

C# Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9

Common Azure Tools   1.10

Extensibility Message Bus   1.4.39 (main@e8108eb)

Microsoft Azure Hive Query Language Service   2.6.5000.0

Microsoft Azure Stream Analytics Language Service   2.6.5000.0

Microsoft JVM Debugger   1.0

Mono Debugging for Visual Studio   17.11.3 (ba13144)

NuGet Package Manager   6.11.1

Oracle Developer Tools for Visual Studio   21.11.0.0

Razor (ASP.NET Core)   17.11.3.2442001+68650a7d94261bc56a1f4bc522c2ee35314b1abb

SQL Server Data Tools   17.11.47.0

ToolWindowHostedEditor   1.0

TypeScript Tools   17.0.30715.2002

Visual Basic Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9

Visual F# Tools   17.11.0-beta.24421.7+af2f522de602281d4ef5a7b71507c428e814c5c1

Visual Studio IntelliCode   2.2

VisualStudio.DeviceLog   1.0

VisualStudio.Mac   1.0

VSPackage Extension   1.0

Xamarin   17.11.0.98 (d17-11@86652fe)

Xamarin Designer   17.11.3.11 (remotes/origin/d17-11@cdbb0a4fdd)

Xamarin Templates   17.9.0 (38e87ba)

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)

---
#### Feedback Bot on 10/17/2024, 06:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by kr-124** [comment] 2024-10-18 17:16
Hi, I'm the original poster of the question on the community forum. If you need additional info just let me know

**Comment by jonathanpeppers** [comment] 2024-10-18 17:48
This template:

![Image](https://github.com/user-attachments/assets/2d5a2c81-0891-4e59-b82a-38d45c943ebf)

Runs for me with VS 17.12 Preview 3 and .NET 9 RC 2:

![Image](https://github.com/user-attachments/assets/8771c53b-fcb3-4e43-ba8d-b76b9e506ec2)

I just clicked the play button, do I need to do anything else?

Does the problem go way if you do this on the `*.Droid` project and try again:

![Image](https://github.com/user-attachments/assets/af70f987-14e0-4237-9e21-70f7bf845d15)

**Comment by kr-124** [comment] 2024-10-18 17:56
Jonathan,

That is the wrong template. It is this one that I had the issue with, and that I need to work with:

![Image](https://github.com/user-attachments/assets/e728402c-30d5-4473-8e08-14571d30e7a2)

**Comment by jonathanpeppers** [comment] 2024-10-18 18:48
Sorry, that is the one I used, but I took the wrong screenshot, it looks like:

![Image](https://github.com/user-attachments/assets/b7591fe9-0681-4ae0-962d-bc723926a3f0)

**Comment by kr-124** [comment] 2024-10-18 19:12
No problem. But to answer your question, yes cleaning the .Droid project did not change anything.

Also, as a quick little test, I did check it just now with the Blazor template you used to see if that would work, but the same issue still occurred. So, perhaps it is something on my end that needs to be updated or removed. Maybe something I have installed in VS 2022? And I just updated VS 2022 to the latest release yesterday. 

Other than looking at the console output, which I'll post here, what else can I do as far as troubleshooting this? 

Here is what's in the output window after I tried it with the Blazor template, it appears to be the same in the other one as well... I scanned through it and nothing stood out much upon the initial look. I do notice that the error text I showed in the post mentions AndroidX and there's a few lines in the output referring to AndroidX. I do not know enough about AndroidX in regards to this project to know the relevancy of this, but maybe that could be helpful. 


(sorry for the lengthy wall of text) 

> Start debugging Android application ...
> am start -D -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.testing2/crc64e3a0a74b4988ce03.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.testing2/crc64e3a0a74b4988ce03.MainActivity }
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Private.CoreLib.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Testing2.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Runtime.InteropServices.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnvInit.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnvInit.cs:57 [0x00000].
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Collections.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Mono.Android.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Threading.dll [External]
[nyname.testing2] Late-enabling -Xcheck:jni
[nyname.testing2] Unexpected CPU variant for x86: x86_64.
[nyname.testing2] Known variants: atom, sandybridge, silvermont, kabylake, default
[CompatibilityChangeReporter] Compat change id reported: 171979766; UID 10173; state: ENABLED
[System.out] Sending WAIT chunk
[System.out] Debugger has connected
[System.out] waiting for debugger to settle...
[System.out] waiting for debugger to settle...
[System.out] waiting for debugger to settle...
[System.out] waiting for debugger to settle...
[System.out] waiting for debugger to settle...
[System.out] waiting for debugger to settle...
[System.out] debugger has settled (1390)
[nativeloader] Configuring classloader-namespace for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64:/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.testing2
[nativeloader] Configuring classloader-namespace for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64:/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.testing2
[ziparchive] Unable to open '/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.dm': No such file or directory
[ziparchive] Unable to open '/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.dm': No such file or directory
[nativeloader] Configuring classloader-namespace for other apk /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64:/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.testing2
[GraphicsEnvironment] ANGLE Developer option for 'com.companyname.testing2' set to: 'default'
[GraphicsEnvironment] ANGLE GameManagerService for com.companyname.testing2: false
[GraphicsEnvironment] Neither updatable production driver nor prerelease driver is supported.
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.testing2/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.testing2/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.testing2/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64/libmonosgen-2.0.so
[nyname.testing2] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[DOTNET] GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
[monodroid] Creating public update directory: `/data/user/0/com.companyname.testing2/files/.__override__`
[nyname.testing2] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:57356,embedding=1,timeout=1729277015
[monodroid-assembly] open_from_bundles: failed to load assembly Testing2.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Diagnostics.StackTrace.dll [External]
[nyname.testing2] Attempt to remove non-JNI local reference, dumping thread
Loaded assembly: data-0x76fadb2e1060 [External]
Loaded assembly: data-0x76fadb2f1070 [External]
Loaded assembly: data-0x76fb88e82650 [External]
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/netstandard.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Linq.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:425 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Text.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Text.Encodings.Web.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.ComponentModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.MobileTapContracts.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Microsoft.Maui.Controls.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Microsoft.Maui.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:420 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Reflection.Primitives.dll [External]
[AndroidRuntime] Shutting down VM
**Java.Lang.NoClassDefFoundError:** 'Failed resolution of: Landroidx/startup/R$string;'

>[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.testing2, PID: 23316
[AndroidRuntime] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/startup/R$string;
[AndroidRuntime] 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
[AndroidRuntime] 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
[AndroidRuntime] 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
[AndroidRuntime] 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7872)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.R$string" on path: DexPathList[[zip file "/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/lib/x86_64, /data/app/~~xcLqUJzKLOfQ3wqLAKVjxA==/com.companyname.testing2-5tQMFbFKdXpUaXZK7MMzdQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	... 17 more
[monodroid-assembly] open_from_bundles: failed to load assembly System.Console.dll
Loaded assembly: /data/data/com.companyname.testing2/files/.__override__/System.Console.dll [External]

**Comment by jonathanpeppers** [comment] 2024-10-18 19:24
Can you save a `.binlog` of a Rebuild? https://aka.ms/binlog

**Comment by kr-124** [comment] 2024-10-22 18:00
Jonathan,

Sorry for the slight delay. I followed the steps there and it appears to have produced 3 .binlog files. Not sure which you need so I am adding all 3 and placing them in a zip file for you. If there's anything I can do to narrow these down let me know. [binlogs.zip](https://github.com/user-attachments/files/17480364/binlogs.zip)

**Comment by jonathanpeppers** [comment] 2024-10-22 21:37
The `.binlog` shows this an an input to `javac`:

![Image](https://github.com/user-attachments/assets/52f47b0a-9d49-4392-8fc4-c77363ce8668)

That looks correct. So, the type it complains about should exist:

```
'Failed resolution of: Landroidx/startup/R$string;'
```

Two things could help us investigate further. Can you share the contents of:

* `obj\Debug\net8.0-android\android\src\androidx\startup\R.java`
* `bin\Debug\net8.0-android\com.companyname.newmauiapp-Signed.apk`

If the `R.java` file looks right, I can open the `.apk` in Android Studio to inspect the contents.

**Comment by kr-124** [comment] 2024-10-23 14:10
Sure, here is a zip file with both of those 
[Debug items.zip](https://github.com/user-attachments/files/17492992/Debug.items.zip)

**Comment by jonathanpeppers** [comment] 2024-10-23 14:20
Seems like `R.java` is empty:
```java
/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by
 * Xamarin.Android from the resource data it found.
 * It should not be modified by hand.
 */
package androidx.startup;

public final class R {
}

```

**Comment by jonathanpeppers** [comment] 2024-10-23 14:24
The `.binlog` files above don't show this task running at all:

![Image](https://github.com/user-attachments/assets/59ec771d-db70-4b97-875c-d60ebd0d4b75)

It should be the one that creates the file above. It was likely just skipped because this was an incremental build or something.

So, I think we just need to check a full build:

* Make sure this is selected:

![Image](https://github.com/user-attachments/assets/5b9b758c-a74b-426c-87ca-ab2b8b341561)

* Do a `Rebuild` and save the logs from there.

**Comment by kr-124** [comment] 2024-10-23 14:38
Okay, did that and here are the new binlogs that were generated. It made 4 this time, and again I'll just zip them all up and give them to you in case all of them contain useful information.

[binlogs.zip](https://github.com/user-attachments/files/17493529/binlogs.zip)

**Comment by kr-124** [comment] 2024-10-23 15:24
Sorry, I just happened to re-read what you said. I built it before, but didn't do a _rebuild_, that is my fault for misreading. I can see how that would cause inaccurate logging for our purposes here, so I will repeat the process with a rebuild and update in a minute or two.

**Comment by kr-124** [comment] 2024-10-23 15:41
Okay so the zip file "Rebuild binlogs 1" is the binlogs it produced after I rebuilt the solution, but did not attempt to deploy it to my emulator. I then clicked the button to run it on the emulator. "Rebuild binlogs 2" is the binlogs that were produced after that. Took a little longer because the debugger got stuck and I had to retry it. Hopefully the second set of logs are still accurate.

[Rebuild binlogs 1.zip](https://github.com/user-attachments/files/17494580/Rebuild.binlogs.1.zip)
[Rebuild binlogs 2.zip](https://github.com/user-attachments/files/17494697/Rebuild.binlogs.2.zip)

**Comment by jonathanpeppers** [comment] 2024-10-28 15:59
The `GenerateLibraryResources` task printed around 22,000 lines like this:
```
C:\Source\TestProjectSourceFolder\NewMauiApp\NewMauiApp\NewMauiApp.Droid\obj\Debug\net8.0-android\lp\155\jl\R.txt: `int styleable ViewStubCompat_android_id` value not found
C:\Source\TestProjectSourceFolder\NewMauiApp\NewMauiApp\NewMauiApp.Droid\obj\Debug\net8.0-android\lp\155\jl\R.txt: `int styleable ViewStubCompat_android_inflatedId` value not found
C:\Source\TestProjectSourceFolder\NewMauiApp\NewMauiApp\NewMauiApp.Droid\obj\Debug\net8.0-android\lp\155\jl\R.txt: `int styleable ViewStubCompat_android_layout` value not found
```
So, I wonder if many of the `R.txt` files (inputs) are also empty, like this file should be from `OriginalFile = C:\Users\kragan\.nuget\packages\xamarin.androidx.startup.startupruntime\1.1.1.7\aar\androidx.startup.startup-runtime.aar`
```
C:\Source\TestProjectSourceFolder\NewMauiApp\NewMauiApp\NewMauiApp.Droid\obj\Debug\net8.0-android\lp\92\jl\res\..\R.txt
```

One think you could try is to clear your NuGet cache, the `C:\Users\kragan\.nuget\packages\` folder.

/cc @dellis1972

**Comment by dellis1972** [comment] 2024-10-28 16:02
I checked my files and get 

```
unzip -lvc ~/.nuget/packages/xamarin.androidx.startup.startupruntime/1.1.1.9/aar/androidx.startup.startup-runtime.aar R.txt
Archive:  /Users/<user>/.nuget/packages/xamarin.androidx.startup.startupruntime/1.1.1.9/aar/androidx.startup.startup-runtime.aar
  inflating: R.txt                   
int string androidx_startup 0x0
```

So in my case both the R.txt and the `res/values.xml` have the data.

**Comment by kr-124** [comment] 2024-11-06 16:33
Hey @jonathanpeppers (or @dellis1972) been a bit busy but I was just looking at your last updates. I cleared the NuGet cache (went to Tools → NuGet Package Manager → Package Manager Settings and clicked the Clear All NuGet Storage button). I'm still getting the same runtime error pop up after doing that (Java.Lang.NoClassDefFoundError: 'Failed resolution of: Landroidx/startup/R$string;'). 

As far as the path you mentioned, ~\.nuget\packages\xamarin.androidx.startup.startupruntime, within that I have folders for 1.1.1.6 AND 1.1.1.7. Is that a potential issue, perhaps? If not, any other information I can give you or things I can try?

**Comment by kr-124** [comment] 2024-11-06 19:45
Also wanted to add this and show you what these filepaths look like since they were mentioned. Plus show you what the "values" file appears like for me - it's not empty but I'm not sure what this tells us.

![Image](https://github.com/user-attachments/assets/2d599319-2d23-480b-a919-f751fbff083e)
![Image](https://github.com/user-attachments/assets/5c709d3a-05da-4458-ab30-9d361a29a868)
![Image](https://github.com/user-attachments/assets/277ecd1e-bd82-44e7-ae98-83537b8f2325)

**Comment by kr-124** [comment] 2024-11-13 15:57
I have an update - I happened to update Visual Studio 2022 to the most recent version that was just put out, and decided to run this again, and it appears to have worked. Not sure what changed but here is the new basic info in case it helps anyone:

Microsoft Visual Studio Professional 2022
Version 17.12.0
VisualStudio.17.Release/17.12.0+35506.116
Microsoft .NET Framework
Version 4.8.09037

You guys can probably close this if you don't have anything else to add. Thank you for your time!

**Closed** 2024-11-13 16:27 UTC
Labels: Area: App+Library Build, need-attention
